[build]
  functions = "functions"
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing - MUST be after API redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers configuration
[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/xml"